apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: static-pvc
    namespace: default
  csi:
    driver: "csi.vsphere.vmware.com"
    volumeAttributes:
      type: "vSphere CNS Block Volume"
      storage.kubernetes.io/csiProvisionerIdentity: "1595466506881-8081-csi.vsphere.vmware.com"  # Is this needed?
    "volumeHandle": "9a00143c-7b0e-4c01-82d5-5818e0dec31b"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "block-sc"
  volumeName: "static-pv"
